name: Code Fixer

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish formatted code'

jobs:
  fix_python_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Format Python code
        run: |
          black --exclude migrations .

  publish_formatted_code:
    runs-on: ubuntu-latest
    needs: [fix_python_code]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Commit changes
        run: |
          git commit -am "chore: code formatting" --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
